name: âœ… JSON Sorting

on:
  push:
    paths:
      - '*.json'
    branches:
      - main
  workflow_dispatch:

jobs:  
  sorting:
    name: JSON Sorting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JSON Sorting
        run: |
          jq '.programs |= sort_by(.name | ascii_downcase)' chaos-bugbounty-list.json > chaos-bugbounty-list.json.tmp && mv chaos-bugbounty-list.json.tmp chaos-bugbounty-list.json

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Automatic JSON Sorting [$(date)] :robot:" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}